[profile.default]
src = "contracts"
out = "out"
solc = "0.8.23"
libs = ["node_modules", "lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
